### ISSUE TITLE
Suggestion: Improve MinIO Setup and Configuration

### ISSUE THREAD

**Issue by carlmes** [redhat-ai-services/ai-accelerator#78]
A suggestion for some minor improvements to the MinIO configuration in the `components/apps/minio` location:

- Randomize the MinIO admin user name and password instead of minio123, since the AWS demo clusters are internet facing. 
- Add an OpenShift Application Menu using a ConsoleLink object, so that uses can easily access the admin UI

There's a great example in the [Fraud Detection Demo](https://docs.redhat.com/en/documentation/red_hat_openshift_ai_cloud_service/1/html-single/openshift_ai_tutorial_-_fraud_detection_example/index#running-a-script-to-install-storage), specifically this script that we could copy some logic / content from:

`oc apply -n <your-project-name/> -f https://github.com/rh-aiservices-bu/fraud-detection/raw/main/setup/setup-s3.yaml`

Example ConsoleLink:

```
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: link-minio
spec:
  href: "https://minio-console-fraud-detection.apps.cluster-zk244.zk244.sandbox1964.opentlc.com/"
  location: ApplicationMenu
  text: MinIO Console
  applicationMenu:
    section: AI Applications
    imageURL: https://min.io/resources/favs/favicon-32x32.png
```
